require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Lint/ImplicitStringConcatenation:
  Exclude:
  #everything here was hyrax-specific

#debugger calls are expected within specs in normal operation
Lint/Debugger:
  Exclude:
    - 'spec/**/*'

# unrelated javascript error interferes with spec execution
Lint/HandleExceptions:
  Exclude:
    - 'spec/features/doi_validation_spec.rb'

Metrics/LineLength:
  Max: 400

Metrics/AbcSize:
  Max: 30
  Exclude:
  #everything here was hyrax-specific
    - 'app/indexers/hyrax/file_set_indexer.rb'
    - 'app/helpers/change_manager/change_manager_helper.rb'
    - 'app/forms/hyrax/forms/batch_edit_form.rb'
    - 'app/indexers/hyrax/work_indexer.rb'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'lib/seed_methods.rb'
    - 'app/indexers/hyrax/file_set_indexer.rb'
    - 'spec/support/hyrax/factory_helpers.rb'
    - 'app/helpers/change_manager/change_manager_helper.rb'
    - 'app/forms/hyrax/forms/batch_upload_form.rb'
    - 'app/forms/hyrax/forms/batch_edit_form.rb'
    - 'app/controllers/classify_concerns_controller.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/seed_methods.rb'
    - 'app/helpers/hyrax_helper.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/helpers/change_manager/change_manager_helper.rb'
    - 'app/forms/hyrax/forms/batch_edit_form.rb'
    - 'app/helpers/hyrax_helper.rb'    

Metrics/CyclomaticComplexity:
  Exclude:
  - 'app/forms/hyrax/forms/batch_upload_form.rb'
  - 'app/forms/hyrax/forms/batch_edit_form.rb'
  - 'app/helpers/hyrax_helper.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/FileName:
  Exclude:
    - 'Gemfile'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'app/controllers/contact_form_controller.rb'
    - 'app/controllers/concerns/hyrax/contact_form_controller_behavior.rb'
    - 'bin/*'

Style/GuardClause:
  Exclude:
    - 'app/models/ability.rb'
    - 'app/indexers/hyrax/collection_indexer.rb'
    - 'app/indexers/hyrax/work_indexer.rb'
    - 'app/services/change_manager/email_manager.rb'

Style/SymbolProc: # https://github.com/bbatsov/rubocop/issues/3071
  Exclude:
  #everything here was hyrax-specific

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/BracesAroundHashParameters:
  Exclude:
    - 'spec/controllers/workgroups_controller_spec.rb'
    - 'spec/views/workgroups/edit.html.erb_spec.rb'
    - 'spec/views/workgroups/index.html.erb_spec.rb'
    - 'spec/views/workgroups/new.html.erb_spec.rb'
    - 'spec/views/workgroups/show.html.erb_spec.rb'

Style/CommentIndentation:
  Exclude:
    - 'config/initializers/orcid_initializer.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/RedundantSelf:
  Exclude:
    - 'config/application.rb'
    - 'config/environments/test.rb'

Style/DoubleNegation:
  Exclude:
    - 'config/environments/development.rb'

Style/EmptyLineAfterMagicComment:
  Enabled: false

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/user.rb'
    - 'app/jobs/user_edit_profile_event_job.rb'

Rails/OutputSafety:
  Exclude:
    - app/values/universal_viewer.rb

RSpec/AnyInstance:
  Exclude:
    - 'spec/controllers/hyrax/contact_form_controller_spec.rb'
    - 'spec/features/admin_admin_set_spec.rb'
    - 'spec/controllers/hyrax/etds_controller_spec.rb'
    - 'spec/features/create_work_spec.rb'
    - 'spec/features/end_to_end_spec.rb'
    - 'spec/support/shared/doi_request.rb'
    - 'spec/models/hyrax/ability_spec.rb'
    - 'spec/controllers/collection_avatars_controller_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'
    - 'spec/features/*'
    - 'spec/controllers/hyrax/generic_works_controller_spec.rb'
    - 'spec/routing/hyrax_spec.rb'

RSpec/DescribedClass:
  Exclude:
    - 'spec/presenters/hyrax/work_show_presenter_spec.rb'

Rails/DynamicFindBy:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/*'
    - 'spec/support/shared/*'
    - 'spec/forms/hyrax/forms/batch_edit_form_spec.rb'
    - 'spec/jobs/batch_create_job_spec.rb'

RSpec/SubjectStub:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/features/browse_catalog_spec.rb'
