# frozen_string_literal: true
# Generated by curation_concerns:models:install
class Collection < ActiveFedora::Base
  include ::CurationConcerns::CollectionBehavior
  include Sufia::Collections::Featured
  # You can replace these metadata if they're not suitable
  include CurationConcerns::BasicMetadata
end
