# frozen_string_literal: true
# Generated by curation_concerns:models:install
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  include Hyrax::Collections::Featured
  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata
end
